version: '3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: frostan/kittygram_backend
    env_file: .env
    volumes:
      - static:/static_backend
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: frostan/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: frostan/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static_backend
      - media:/media
    ports:
      - 9000:80
